import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { FaEye, FaPlus, FaRedo } from "react-icons/fa";
import AdminLayout from "../components/AdminLayout.jsx";
import Metrics from "../components/Metrics.jsx";
import { getAdminRequests, getDashboard } from "../services/api";
import "../App.css";

function QuickActions() { return <section className="quick-actions"><h2 className="quick-actions-title">Quick Administrative Actions</h2><div className="buttons-row"><Link className="button button-primary" to="/admin/products"><FaPlus />Add Product</Link><Link className="button button-primary" to="/admin/services"><FaPlus />Add Service</Link><Link className="button button-secondary" to="/admin/requests"><FaEye />View Pending Requests</Link></div></section>; }
function normalizeMetrics(data) { const metrics = data.metrics || data; return { totalActiveProducts: metrics.total_active_products, inStockProducts: metrics.in_stock_products, lowStockProducts: metrics.low_stock_products, outOfStockProducts: metrics.out_of_stock_products, pendingProductRequests: metrics.pending_product_requests, pendingServiceRequests: metrics.pending_service_requests }; }
function requestRows(data) { const list = Array.isArray(data) ? data : data.requests || data.items || []; return list.slice(0, 10).map((request) => ({ id: request.id || request._id || request.request_id || "—", customer: request.customer_name || request.customer || "—", type: request.request_type || request.type || "—", item: request.product_name || request.service_name || request.item_name || request.product_service || "—", quantity: request.quantity ?? "—", status: request.status || "New", date: request.created_at || request.date || "—" })); }
function formatDate(value) { if (!value || value === "—") return value; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(date); }
function RecentInquiries({ requests, isLoading }) { return <section className="table-container"><div className="table-header-title-bar"><h2>Recent Customer Inquiries</h2></div><div className="inquiries-table-wrapper"><table className="inquiries-table"><thead><tr><th>Request ID</th><th>Customer Name</th><th>Type</th><th>Item Name</th><th>Qty</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>{isLoading ? Array.from({ length: 4 }, (_, index) => <tr key={index}>{Array.from({ length: 8 }, (_, cell) => <td key={cell}><span className="table-skeleton" /></td>)}</tr>) : requests.length > 0 ? requests.map((request) => <tr key={request.id}><td>{request.id}</td><td>{request.customer}</td><td>{request.type}</td><td>{request.item}</td><td className="qty-cell">{request.quantity}</td><td><span className={`status-badge status-${String(request.status).toLowerCase().replaceAll(" ", "-")}`}>{request.status}</span></td><td>{formatDate(request.date)}</td><td><div className="inquiry-actions"><Link className="inquiry-action-btn" to="/admin/requests" aria-label={`View ${request.id}`}><FaEye /></Link></div></td></tr>) : <tr><td className="dashboard-empty" colSpan="8">No recent requests found.</td></tr>}</tbody></table></div></section>; }
function DashboardError({ message, onRetry }) { return <section className="dashboard-error" role="alert"><div><strong>Dashboard unavailable</strong><p>{message}</p></div><button className="button button-primary" type="button" onClick={onRetry}><FaRedo />Retry</button></section>; }
function Admin() { const [dashboard, setDashboard] = useState(null); const [requests, setRequests] = useState([]); const [error, setError] = useState(""); const [isLoading, setIsLoading] = useState(true); const loadDashboard = useCallback(async () => { setIsLoading(true); setError(""); try { const result = await getDashboard(); setDashboard(normalizeMetrics(result)); if (Array.isArray(result.recent_requests)) { setRequests(requestRows(result.recent_requests)); } else { try { setRequests(requestRows(await getAdminRequests())); } catch (requestError) { if (import.meta.env.DEV) console.error("[MIFRA Dashboard] Recent requests fallback failed", { status: requestError.status, message: requestError.message }); setRequests([]); } } } catch (loadError) { if (import.meta.env.DEV) console.error("[MIFRA Dashboard] Dashboard request failed", { status: loadError.status, message: loadError.message }); setError(loadError.message || "We could not load dashboard data. Please try again."); } finally { setIsLoading(false); } }, []); useEffect(() => { loadDashboard(); }, [loadDashboard]); return <AdminLayout><section className="dashboard-header"><div><p className="eyebrow">Operations overview</p><h1>Business at a glance</h1><p>Monitor products, customer inquiries, and service activity.</p></div></section>{error ? <DashboardError message={error} onRetry={loadDashboard} /> : <section className="scroll-content"><Metrics metrics={dashboard} isLoading={isLoading} /><QuickActions /><RecentInquiries requests={requests} isLoading={isLoading} /></section>}</AdminLayout>; }
export default Admin;
