import { useEffect, useMemo, useState } from "react";
import { FaEdit, FaPlus, FaTrash } from "react-icons/fa";
import AdminLayout from "../components/AdminLayout";
import { DataTable, FormField, Modal, PageHeader, StatusBadge, Toggle } from "../components/AdminUI";
import { createAdminProduct, deleteAdminProduct, getAdminProducts, getCategories, updateAdminProduct } from "../services/api";

const emptyProduct = { name: "", description: "", price: "", category: "", image: "", stockQuantity: "", lowStockThreshold: "5", isActive: true, featured: false };

function ProductForm({ product, categories, onClose, onSave }) {
	const [form, setForm] = useState(product || emptyProduct);
	const [formError, setFormError] = useState("");
	const [saving, setSaving] = useState(false);
	const isEditing = Boolean(product);
	const setField = (field, value) => setForm((current) => ({ ...current, [field]: value }));
	const handleSubmit = async (event) => {
		event.preventDefault();
		if (!form.name.trim() || !form.description.trim() || !form.category.trim() || form.price === "" || form.stockQuantity === "" || form.lowStockThreshold === "") { setFormError("Please complete all required fields."); return; }
		const price = Number(form.price); const stockQuantity = Number(form.stockQuantity); const lowStockThreshold = Number(form.lowStockThreshold);
		if (!Number.isFinite(price) || !Number.isInteger(stockQuantity) || !Number.isInteger(lowStockThreshold) || price < 0 || stockQuantity < 0 || lowStockThreshold < 0) { setFormError("Enter valid non-negative numbers for price and stock values."); return; }
		setSaving(true); setFormError("");
		try { await onSave({ ...form, name: form.name.trim(), description: form.description.trim(), category: form.category.trim(), image: form.image.trim() || null, price, stockQuantity, lowStockThreshold }); } catch (error) { setFormError(error.message); setSaving(false); }
	};
	return <Modal title={isEditing ? "Edit Product" : "Add Product"} onClose={onClose}><form className="admin-form" onSubmit={handleSubmit}><div className="form-grid"><FormField label="Name" placeholder="Product name" value={form.name} onChange={(event) => setField("name", event.target.value)} /><FormField label="Price" type="number" placeholder="0.00" value={form.price} onChange={(event) => setField("price", event.target.value)} /><FormField label="Category"><select value={form.category} onChange={(event) => setField("category", event.target.value)}><option value="" disabled>Select a category</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></FormField><FormField label="Image URL" placeholder="https://..." value={form.image} onChange={(event) => setField("image", event.target.value)} /><FormField label="Stock Quantity" type="number" placeholder="0" value={form.stockQuantity} onChange={(event) => setField("stockQuantity", event.target.value)} /><FormField label="Low Stock Threshold" type="number" placeholder="5" value={form.lowStockThreshold} onChange={(event) => setField("lowStockThreshold", event.target.value)} /></div><FormField label="Description" textarea placeholder="Brief product description" value={form.description} onChange={(event) => setField("description", event.target.value)} /><div className="toggle-row"><Toggle label="Active" checked={form.isActive} onChange={(event) => setField("isActive", event.target.checked)} /><Toggle label="Featured" checked={form.featured} onChange={(event) => setField("featured", event.target.checked)} /></div>{formError && <p className="form-error" role="alert">{formError}</p>}<div className="form-actions"><button className="button button-secondary" type="button" onClick={onClose}>Cancel</button><button className="button button-primary" type="submit" disabled={saving}>{saving ? "Saving..." : "Save Product"}</button></div></form></Modal>;
}

function Products() {
	const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [feedback, setFeedback] = useState(""); const [showForm, setShowForm] = useState(false); const [editingProduct, setEditingProduct] = useState(null); const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [availability, setAvailability] = useState(""); const [sort, setSort] = useState("");
	const loadProducts = async () => { setLoading(true); setError(""); try { const data = await getAdminProducts(); setProducts(Array.isArray(data) ? data : data?.products || []); } catch (loadError) { setError(loadError.message); } finally { setLoading(false); } };
	useEffect(() => {
		let isMounted = true;
		Promise.all([getAdminProducts(), getCategories()]).then(([productData, categoryData]) => { if (!isMounted) return; setProducts(Array.isArray(productData) ? productData : productData?.products || []); setCategories(Array.isArray(categoryData) ? categoryData : categoryData?.categories || []); }).catch((loadError) => { if (isMounted) setError(loadError.message); }).finally(() => { if (isMounted) setLoading(false); });
		return () => { isMounted = false; };
	}, []);
	const categoryName = (value) => { const categoryId = typeof value === "object" ? value?.id : value; const match = categories.find((item) => String(item.id) === String(categoryId)); return match?.name || (typeof value === "object" ? value?.name : null) || "Unknown Category"; };
	const categoryId = (value) => typeof value === "object" ? value?.id || "" : value || "";
	const visibleProducts = useMemo(() => products.filter((product) => product.isActive === true && product.name.toLowerCase().includes(search.toLowerCase()) && (!category || String(categoryId(product.category)) === String(category)) && (!availability || (availability === "In Stock" ? product.stockQuantity > product.lowStockThreshold : availability === "Limited Stock" ? product.stockQuantity > 0 && product.stockQuantity <= product.lowStockThreshold : product.stockQuantity === 0))).sort((first, second) => sort === "name" ? first.name.localeCompare(second.name) : sort === "price" ? first.price - second.price : sort === "newest" ? new Date(second.createdAt || 0) - new Date(first.createdAt || 0) : 0), [products, search, category, availability, sort]);
	const statusFor = (product) => product.stockQuantity === 0 ? "Out of Stock" : product.stockQuantity <= product.lowStockThreshold ? "Limited Stock" : "In Stock";
	const productId = (product) => product.id || product._id || product.product_id;
	const openAdd = () => { setEditingProduct(null); setShowForm(true); }; const openEdit = (product) => { setEditingProduct({ ...product, category: categoryId(product.category), image: product.image || "" }); setShowForm(true); };
	const saveProduct = async (payload) => { if (editingProduct) await updateAdminProduct(productId(editingProduct), payload); else await createAdminProduct(payload); setShowForm(false); setFeedback(editingProduct ? "Product updated successfully." : "Product added successfully."); await loadProducts(); };
	const removeProduct = async (product) => { if (!window.confirm(`Deactivate ${product.name}?`)) return; try { await deleteAdminProduct(productId(product)); setProducts((current) => current.map((item) => productId(item) === productId(product) ? { ...item, isActive: false } : item)); setFeedback("Product deactivated successfully."); await loadProducts(); } catch (deleteError) { setError(deleteError.message); } };
	return <AdminLayout><PageHeader title="Products" description="Manage your product catalogue" action={<button className="button button-primary" type="button" onClick={openAdd}><FaPlus />Add Product</button>} />{feedback && <p className="success-message" role="status">{feedback}</p>}{error && <div className="error-message" role="alert"><span>{error}</span><button className="button button-secondary" type="button" onClick={loadProducts}>Retry</button></div>}<div className="filter-bar"><label className="filter-search"><span aria-hidden="true">⌕</span><input type="search" placeholder="Search products..." aria-label="Search products" value={search} onChange={(event) => setSearch(event.target.value)} /></label><label className="filter-select"><span>Category</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">All Category</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="filter-select"><span>Availability</span><select value={availability} onChange={(event) => setAvailability(event.target.value)}><option value="">All Availability</option><option>In Stock</option><option>Limited Stock</option><option>Out of Stock</option></select></label><label className="filter-select"><span>Sort</span><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="">Newest</option><option value="name">Name</option><option value="price">Price</option></select></label></div>{loading ? <p className="loading-state">Loading products...</p> : <DataTable columns={["Product", "Category", "Price", "Stock", "Status", "Featured", "Actions"]} label={`Showing ${visibleProducts.length} of ${products.length} products`}>{visibleProducts.length ? visibleProducts.map((product) => <tr key={productId(product)}><td><strong>{product.name}</strong></td><td>{categoryName(product.category)}</td><td>${Number(product.price).toLocaleString()}</td><td>{product.stockQuantity}</td><td><StatusBadge status={statusFor(product)} kind="stock" /></td><td>{product.featured ? <span className="featured-mark">Featured</span> : "-"}</td><td><div className="table-actions"><button className="icon-button" type="button" aria-label={`Edit ${product.name}`} onClick={() => openEdit(product)}><FaEdit /></button><button className="icon-button danger-icon" type="button" aria-label={`Delete ${product.name}`} onClick={() => removeProduct(product)}><FaTrash /></button></div></td></tr>) : <tr><td colSpan="7">No products found.</td></tr>}</DataTable>}{showForm && <ProductForm product={editingProduct} categories={categories} onClose={() => setShowForm(false)} onSave={saveProduct} />}</AdminLayout>;
}
export default Products;
